# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forminputv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QMainWindow,QApplication, QCalendarWidget,QLabel
from PyQt5 import QtWidgets,QtCore,QtGui
from PyQt5 import uic
import pymysql
import sys


class Ui_forminput(object):
   
    def koneksi(self):
        konek=pymysql.connect(db='databasebuatan',user='root',passwd='karkun54',host='localhost',port=3306,autocommit=True)
        con=konek.cursor
            
        if (con):
            self.kotakpesan("Koneksi","Koneksi Berhasil")
        else:
            self.kotakpesan("Koneksi","Koneksi Gagal")
        
    def kotakpesan(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowTitle("pesan")
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
            
    def save(self):
        nip=self.lineEdit.text()
        nama=self.lineEdit_2.text()
        divisi=self.comboBox.currentText()
        grade=self.comboBox_2.currentText()
    

        masuk=str(self.calendarWidget.selectedDate())[19:29]
        
        foto=self.textEdit.toPlainText()
        
        lahir=str(self.calendarWidget_2.selectedDate())[19:29]
        alamat=self.lineEdit_2.text()
        insert=nip,nama,divisi,grade,masuk,foto,lahir,alamat
        konek=pymysql.connect(db='databasebuatan',user='root',passwd='karkun54',host='localhost',port=3306,autocommit=True)
        con=konek.cursor()
        
        
        sql="insert into databasebuatan.pegawai(nip,nama,divisi,grade,masuk,foto,lahir,alamat) values"+ str(insert)
        
        try:
            bisa=con.execute(sql)
            tes=con.fetchall()
            if (bisa):
                self.kotakpesan("sukses","data tersimpan")
        
            
            else:
                
                self.kotakpesan("gagal","data gagal tersimpan")
        
        except pymysql.IntegrityError as e:
            self.kotakpesan("afa","pesan")

    
       
        
        

    
    def setupUi(self, forminput):
        
        self.koneksi()
        forminput.setObjectName("forminput")
        forminput.resize(846, 677)
        self.centralwidget = QtWidgets.QWidget(forminput)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 60, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 30, 161, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 90, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 60, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 130, 104, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(445, 30, 211, 141))
        self.graphicsView.setObjectName("graphicsView")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 91, 16))
        self.label_5.setObjectName("label_5")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(120, 200, 231, 181))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 180, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 200, 60, 16))
        self.label_7.setObjectName("label_7")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(450, 220, 221, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(450, 310, 101, 21))
        self.label_8.setObjectName("label_8")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget_2.setGeometry(QtCore.QRect(450, 330, 312, 173))
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.save())
        self.pushButton.setGeometry(QtCore.QRect(90, 540, 113, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(620, 540, 113, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(450, 510, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        forminput.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(forminput)
        self.statusbar.setObjectName("statusbar")
        forminput.setStatusBar(self.statusbar)

        self.retranslateUi(forminput)
        QtCore.QMetaObject.connectSlotsByName(forminput)
        
       

    def retranslateUi(self, forminput):
        _translate = QtCore.QCoreApplication.translate
        forminput.setWindowTitle(_translate("forminput", "MainWindow"))
        self.label.setText(_translate("forminput", "NIP"))
        self.label_2.setText(_translate("forminput", "NAMA"))
        self.label_3.setText(_translate("forminput", "DIVISI"))
        self.label_4.setText(_translate("forminput", "GRADE"))
        self.comboBox.setItemText(0, _translate("forminput", "IT"))
        self.comboBox.setItemText(1, _translate("forminput", "TEKNIK"))
        self.comboBox.setItemText(2, _translate("forminput", "KEUANGAN"))
        self.comboBox.setItemText(3, _translate("forminput", "UMUM"))
        self.comboBox.setItemText(4, _translate("forminput", "OPERASI"))
        self.comboBox_2.setItemText(0, _translate("forminput", "1"))
        self.comboBox_2.setItemText(1, _translate("forminput", "2"))
        self.comboBox_2.setItemText(2, _translate("forminput", "3"))
        self.comboBox_2.setItemText(3, _translate("forminput", "4"))
        self.comboBox_2.setItemText(4, _translate("forminput", "5"))
        self.comboBox_2.setItemText(5, _translate("forminput", "6"))
        self.comboBox_2.setItemText(6, _translate("forminput", "7"))
        self.comboBox_2.setItemText(7, _translate("forminput", "8"))
        self.comboBox_2.setItemText(8, _translate("forminput", "9"))
        self.comboBox_2.setItemText(9, _translate("forminput", "10"))
        self.comboBox_2.setItemText(10, _translate("forminput", "11"))
        self.comboBox_2.setItemText(11, _translate("forminput", "12"))
        self.comboBox_2.setItemText(12, _translate("forminput", "13"))
        self.comboBox_2.setItemText(13, _translate("forminput", "14"))
        self.comboBox_2.setItemText(14, _translate("forminput", "15"))
        self.comboBox_2.setItemText(15, _translate("forminput", "16"))
        self.comboBox_2.setItemText(16, _translate("forminput", "17"))
        self.comboBox_2.setItemText(17, _translate("forminput", "18"))
        self.comboBox_2.setItemText(18, _translate("forminput", "19"))
        self.comboBox_2.setItemText(19, _translate("forminput", "20"))
        self.label_5.setText(_translate("forminput", "Tanggal Masuk"))
        self.label_6.setText(_translate("forminput", "Foto Profil"))
        self.label_7.setText(_translate("forminput", "Alamat"))
        self.label_8.setText(_translate("forminput", "TANGGA LAHIR"))
        self.pushButton.setText(_translate("forminput", "SAVE"))
        self.pushButton_3.setText(_translate("forminput", "CLEAR"))
        self.label_9.setText(_translate("forminput", "TextLabel"))
        self.label_10.setText(_translate("forminput", "TextLabel"))






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    forminput = QtWidgets.QMainWindow()
    ui = Ui_forminput()
    ui.setupUi(forminput)
    forminput.show()
    sys.exit(app.exec_())
