# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_formedit(object):
    
    def tampil(self):
        nama=self.lineEdit_2.text()
        db = pymysql.connect(db='databasebuatan', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cursor = db.cursor()
        cursor.execute("SELECT * FROM pegawai WHERE nip = '" + str(nama) + "'")
        data = cursor.fetchall()
        if(data):
            for tp in data:
                self.lineEdit.setText (str(tp[0]))
                self.comboBox.clear()
                self.comboBox.addItem(str(tp[2]))
            
            arrdivisi=["IT","UMUM","KEUANGAN","OPERASI","TEKNIK","HSSE","PEMASARAN"]
            for divisi in arrdivisi: 
                self.comboBox.addItem(divisi)
                self.comboBox_2.clear()
                self.comboBox_2.addItem(str(tp[3]))
            for grade in range(21):
                self.comboBox_2.addItem(str(grade))       
                self.textEdit_2.setText(str(tp[4]))
                self.textEdit.setText(str(tp[6]))
                self.textEdit_4.setText(str(tp[5]))
                self.textEdit_3.setText(str(tp[7]))
            
                
        else:
            self.comboBox.clear()
            self.comboBox_2.clear()
            self.lineEdit.clear()
            self.comboBox.clear()
            self.comboBox_2.clear()
            self.textEdit_2.clear()
            self.textEdit.clear()
            self.textEdit_4.clear()
            self.textEdit_3.clear()
            self.kotakpesan("INFO", "DATA BELUM ADA SILAKAN INPUT DATA")
    
    def update(self):
        
        varnip=self.lineEdit_2.text()
        varnama=self.lineEdit.text()
        vardivisi=self.comboBox.currentText()
        vargrade=self.comboBox_2.currentText()
        varmasuk=self.textEdit_2.toPlainText()
        varfoto=self.textEdit.toPlainText()
        varalamat=self.textEdit_4.toPlainText()
        varlahir=self.textEdit_3.toPlainText()
        
        con = pymysql.connect(db='databasebuatan', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "UPDATE pegawai SET nip='"+varnip+"',nama='"+varnama+"',divisi='" + vardivisi+"',grade='"+vargrade+"',masuk='"+varmasuk +"',foto='"+varfoto+"',alamat='"+varalamat+"',lahir='"+varlahir+ "' WHERE nip='"+ str(varnip)+"'"
        
        data = cur.execute(sql)
        if(data):
            self.kotakpesan("SUKSES", "Data berhasil di update")
        else:
            self.kotakpesan("GAGAL","NIP tidak bisa dirubah karna NIP permanen")

    def hapus(self):
        varnip=self.lineEdit_2.text()
        con = pymysql.connect(db='databasebuatan', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "Delete from pegawai WHERE nip='"+ str(varnip)+"'"
        
        data = cur.execute(sql)
        if(data):
            self.kotakpesan("SUKSES", "DATA BERHASIL DIHAPUS")
            self.lineEdit_2.setFocus()
            self.textEdit_2.clear()
            self.textEdit.clear()
            self.textEdit_4.clear()
            self.textEdit_3.clear()
            self.comboBox.clear()
            self.comboBox_2.clear()
            self.lineEdit.clear()
            self.lineEdit_2.clear()
            self.comboBox.clear()
            self.comboBox_2.clear()
        else:
            self.kotakpesan("GAGAL", sql)
            
            
    def kotakpesan(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowTitle("PESAN")
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
    
    
    def setupUi(self, formedit):
        
        formedit.setObjectName("formedit")
        formedit.resize(846, 677)
        self.centralwidget = QtWidgets.QWidget(formedit)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 60, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 60, 161, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 90, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget,returnPressed=lambda:self.tampil())
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 30, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 130, 104, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(450, 30, 291, 211))
        self.graphicsView.setObjectName("graphicsView")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 111, 20))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 60, 16))
        self.label_7.setObjectName("label_7")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(130, 240, 281, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 400, 101, 21))
        self.label_8.setObjectName("label_8")
        self.tombolupdate = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.update())
        self.tombolupdate.setGeometry(QtCore.QRect(350, 550, 113, 61))
        self.tombolupdate.setObjectName("tombolupdate")
        self.tomboldelete = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.hapus())
        self.tomboldelete.setGeometry(QtCore.QRect(560, 550, 113, 61))
        self.tomboldelete.setObjectName("tomboldelete")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 190, 161, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(130, 390, 161, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.tombolcari = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.tampil())
        self.tombolcari.setGeometry(QtCore.QRect(150, 550, 113, 61))
        self.tombolcari.setObjectName("tombolcari")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 340, 60, 16))
        self.label_9.setObjectName("label_9")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(130, 330, 281, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        formedit.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(formedit)
        self.statusbar.setObjectName("statusbar")
        formedit.setStatusBar(self.statusbar)

        self.retranslateUi(formedit)
        QtCore.QMetaObject.connectSlotsByName(formedit)

    def retranslateUi(self, formedit):
        _translate = QtCore.QCoreApplication.translate
        formedit.setWindowTitle(_translate("formedit", "EDIT DATA"))
        self.label.setText(_translate("formedit", "NAMA"))
        self.label_2.setText(_translate("formedit", "NIP"))
        self.label_3.setText(_translate("formedit", "DIVISI"))
        self.label_4.setText(_translate("formedit", "GRADE"))
        self.label_5.setText(_translate("formedit", "TANGGAL MASUK"))
        self.label_7.setText(_translate("formedit", "ALAMAT"))
        self.label_8.setText(_translate("formedit", "TANGGAL LAHIR"))
        self.tombolupdate.setText(_translate("formedit", "UPDATE"))
        self.tomboldelete.setText(_translate("formedit", "DELETE"))
        self.tombolcari.setText(_translate("formedit", "CARI"))
        self.label_9.setText(_translate("formedit", "FOTO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formedit = QtWidgets.QMainWindow()
    ui = Ui_formedit()
    ui.setupUi(formedit)
    formedit.show()
    sys.exit(app.exec_())
