# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#import tkinter as tk
from PyQt5 import QtCore, QtGui, QtWidgets
from forminput import Ui_forminput
from formedit import Ui_formedit
from treeviewtampil import Ui_treeviewtampil
#import treeview2

class Ui_MainWindow(object):
    
    def bukainput(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_forminput()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def bukaedit(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_formedit()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def bukatampilsemua (self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_treeviewtampil()
        self.ui.setupUi(self.window)
        self.window.show()
        
    
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 470, 113, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(320, 470, 113, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(590, 470, 113, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:self.bukainput())
        self.pushButton.setGeometry(QtCore.QRect(50, 200, 113, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:self.bukaedit())
        self.pushButton_2.setGeometry(QtCore.QRect(320, 200, 113, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.bukatampilsemua())
        self.pushButton_3.setGeometry(QtCore.QRect(590, 200, 113, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 260, 711, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 120, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 290, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 151, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icon/input-data-1-512.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 90, 131, 101))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../Pictures/icon/database/edit-data-list-512.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(570, 60, 151, 131))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../Pictures/icon/database/view-data-1-512.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 330, 151, 131))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("icon/money-32-512.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 320, 151, 131))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../../Pictures/icon/database/edit-50-512.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(570, 310, 151, 131))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../../../Pictures/icon/database/view-data-1-512.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPegawai = QtWidgets.QMenu(self.menuFile)
        self.menuPegawai.setObjectName("menuPegawai")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPayroll = QtWidgets.QAction(MainWindow)
        self.actionPayroll.setObjectName("actionPayroll")
        self.actionKeluar = QtWidgets.QAction(MainWindow)
        self.actionKeluar.setObjectName("actionKeluar")
        self.actionInput = QtWidgets.QAction(MainWindow)
        self.actionInput.setObjectName("actionInput")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.menuPegawai.addAction(self.actionInput)
        self.menuPegawai.addAction(self.actionEdit)
        self.menuFile.addAction(self.actionPayroll)
        self.menuFile.addAction(self.menuPegawai.menuAction())
        self.menuFile.addAction(self.actionKeluar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("DATA PEGAWAI", "DATA PEGAWAI"))
        self.pushButton_4.setText(_translate("MainWindow", "INPUT GAJI"))
        self.pushButton_5.setText(_translate("MainWindow", "EDIT GAJI"))
        self.pushButton_6.setText(_translate("MainWindow", "VIEW GAJI"))
        self.pushButton.setText(_translate("MainWindow", "INPUT DATA"))
        self.pushButton_2.setText(_translate("MainWindow", "EDIT/CARI"))
        self.pushButton_3.setText(_translate("MainWindow", "VIEW DATA"))
        self.label.setText(_translate("MainWindow", "DATA PEGAWAI"))
        self.label_2.setText(_translate("MainWindow", "PENGGAJIAN"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPegawai.setTitle(_translate("MainWindow", "Pegawai"))
        self.actionPayroll.setText(_translate("MainWindow", "Payroll"))
        self.actionKeluar.setText(_translate("MainWindow", "Keluar"))
        self.actionInput.setText(_translate("MainWindow", "Input"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    #tk.mainloop
