# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treeview.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from PyQt5.QtWidgets import QTableWidgetItem
 

class Ui_treeviewtampil(object):
    
    def select_data(self):
       
        db = pymysql.connect(db='databasebuatan', user='root', passwd='', host='127.0.0.1', port=3306, autocommit=True)
        cursor = db.cursor()
        cursor.execute("SELECT * FROM pegawai")
        data = cursor.fetchall()
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(data):
            #print(row_number)
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                print(column_number)
                self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
 
 
 
    
    def setupUi(self, treeviewtampil):
        
        #self.select_data()
        treeviewtampil.setObjectName("treeviewtampil")
        treeviewtampil.resize(916, 600)
        self.centralwidget = QtWidgets.QWidget(treeviewtampil)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 80, 841, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 30, 441, 20))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.select_data())
        self.pushButton.setGeometry(QtCore.QRect(400, 510, 141, 61))
        self.pushButton.setObjectName("pushButton")
        treeviewtampil.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(treeviewtampil)
        self.statusbar.setObjectName("statusbar")
        treeviewtampil.setStatusBar(self.statusbar)

        self.retranslateUi(treeviewtampil)
        QtCore.QMetaObject.connectSlotsByName(treeviewtampil)

    def retranslateUi(self, treeviewtampil):
        #self.select_data()
        _translate = QtCore.QCoreApplication.translate
        treeviewtampil.setWindowTitle(_translate("treeviewtampil", "DATA MASTER"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("treeviewtampil", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("treeviewtampil", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("treeviewtampil", "4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("treeviewtampil", "NAMA"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("treeviewtampil", "NIP"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("treeviewtampil", "DIVISI"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("treeviewtampil", "GRADE"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("treeviewtampil", "TANGGAL MASUK"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("treeviewtampil", "FOTO"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("treeviewtampil", "ALAMAT"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("treeviewtampil", "TEMPAT LAHIR"))
        self.label.setText(_translate("treeviewtampil", "DATA KARYAWAN PT.ANGIN SEPOI - SEPOI"))
        self.pushButton.setText(_translate("treeviewtampil", "TAMPILKAN DATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    treeviewtampil = QtWidgets.QMainWindow()
    ui = Ui_treeviewtampil()
    ui.setupUi(treeviewtampil)
    treeviewtampil.show()
    sys.exit(app.exec_())
